version: "3.9"

services:
  postgres:
    container_name: postgres-db
    image: postgres:16.2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U etl_user -d etl_job"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - ./scripts/sql/create_table.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=etl_job
      - POSTGRES_USER=etl_user
      - POSTGRES_PASSWORD
  
  etl_job:
    container_name: etl_job
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - API_KEY
      - DB_PASS